### ISSUE TITLE
没找到 proxy.js 文件

### ISSUE THREAD

**Issue by KangodYan** [Eddy0644/ctBridgeBot#13]
![image](https://github.com/Eddy0644/ctBridgeBot/assets/36319737/5365a4fa-39d4-4181-84d5-0e4fdad85d5c)

**Comment by Eddy0644** [comment]
你好，proxy.js文件的模板目前存放在“[config/proxy.js-template](https://github.com/Eddy0644/ctBridgeBot/tree/main/config/proxy.js-template)
”下，若手动部署则应将其复制到data/proxy.js并进行修改。或者，使用static/2.entry.sh进行初始化时脚本也会自动创建该文件。
对于文档中的错谬部分，我将尽快修正。
